export const POKEATHLON_STATS = {
    SPEED: 1, POWER: 2, SKILL: 3, STAMINA: 4, JUMP: 5,
} as const

export const STATS = {
    HP: 1, ATTACK: 2, DEFENSE: 3, SPECIAL_ATTACK: 4,
    SPECIAL_DEFENSE: 5, SPEED: 6, ACCURACY: 7, EVASION: 8,
} as const

export const TYPES = {
    NORMAL: 1, FIGHTING: 2, FLYING: 3, POISON: 4, GROUND: 5,
    ROCK: 6, BUG: 7, GHOST: 8, STEEL: 9, FIRE: 10, WATER: 11,
    GRASS: 12, ELECTRIC: 13, PSYCHIC: 14, ICE: 15, DRAGON: 16,
    DARK: 17, FAIRY: 18, UNKNOWN: 10_001, SHADOW: 10_002,
} as const
